name: Curate packages

on: [push]

jobs:
  curate_genbank:
    name: Curate and export GenBank
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Collect any new commits
        run: |
          git pull  # get any pushes made since the trigger began; without this job-to-job connections may fail

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://test.pypi.org/simple/ -r synbict_scripts/requirements.txt

      - name: Curate GenBank
        run: python3 synbict_scripts/curate_genbank.py

      - name: Commit changes, ready to push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.curated.xml
          git diff-index --quiet HEAD . || git commit -m "Curate GenBank"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
